language: go
go:
  - tip
install:
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
env:
  secure: "K16DOC1qMh1+CPwfdpXm4Ui06SkFCK8YGVubO7S5jXLch2vYw5rnj9KjofxO7u/0q7R2dC/wGitMkQO+BScjDiWwd7/S5DK7Q5NG9B49jFUdCpR5S772Ulg7vfway+UoeA6ziYAkcPhWlCBLVn4P3zULC0UtwfN6xDXPy8w+u8Q="
script:
  - goveralls $COVERALLS_KEY
