language: go
go:
  - tip
install:
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/kr/godep
  - export PATH=$HOME/gopath/bin:$PATH
  - export GOPATH=`godep path`:$GOPATH
env:
  secure: "eDHeYePqPVgroZJPTx5Dao6d9nNV1iVt/4X+yjdFge0LhPSqxrh99O0OSHz/U5gsO9egk+/8vzCYmsvHs5CrI9c0bZ+gAqlm9Ho3LJbqTINSlOX9JIYV2+6SudoRooUJC7F0R6aRfJ5CH8NssIJTcBTx3Lxqxoybs0xNRviLvjw="
script:
  - godep go test -covermode=count -coverprofile=profile.cov
  - goveralls -repotoken=$COVERALLS_KEY -coverprofile=profile.cov -service=travis-ci
